services:
  auto-mcp:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "${AUTO_MCP_SERVER_PORT:-8080}:8080"
    volumes:
      - ./config:/server/config
    environment:
      - AUTO_MCP_SWAGGER_FILE=/server/config/swagger.json
      - AUTO_MCP_ADJUSTMENTS_FILE=/server/config/adjustments.yaml
      - AUTO_MCP_ENDPOINT_BASE_URL=http://petstore.swagger.io/v2
      - AUTO_MCP_MODE=sse
    restart: unless-stopped
