server:
  mode: sse # or stdio
  port: 8080
  host: "localhost"
  timeout: 30s

logging:
  level: "info"
  format: "json"
  color: true
  disable_stacktrace: false
  output_path: "logs/auto-mcp.log"
  append_to_file: true
  disable_console: false

endpoint:
  base_url: "http://localhost:3000"
  auth_type: "bearer"
  auth_config:
    token: "123"

oauth:
  enabled: true
  provider: google
  client_id: ""
  client_secret: ""
  redirect_url: "http://127.0.0.1:6274/oauth/callback"
  scopes: "openid email profile"
  base_url: "http://localhost:8080"
  secure_cookies: false