server:
  mode: sse # or stdio
  port: 8080
  host: "localhost"
  timeout: 30s
  name: "Auto MCP"
  version: "1.0.0"

logging:
  level: "info"
  format: "json"
  color: true
  disable_stacktrace: false
  output_path: "logs/auto-mcp.log"
  append_to_file: true
  disable_console: false

endpoint:
  base_url: "http://localhost:3000"
  auth_type: "bearer"
  auth_config:
    token: "enter_your_token_here"

oauth:
  enabled: true
  provider: github
  client_id: "client_id"
  client_secret: "client_secret"
  scopes: "openid email profile"
  base_url: "http://localhost:8080"
  allow_origins:
    - "http://127.0.0.1:6274" # mcp inspector default endpoint
