services:
  auto-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AUTO_MCP_SERVER_PORT:-8080}:8080"
    volumes:
      - ${SWAGGER_FILE_PATH:?SWAGGER_FILE_PATH is required}:/server/config/swagger.json
      - ${ADJUSTMENTS_FILE_PATH}:/server/config/adjustments.yaml
    environment:
      - AUTO_MCP_SWAGGER_FILE=/server/config/swagger.json
      - AUTO_MCP_ADJUSTMENTS_FILE=/server/config/adjustments.yaml
    restart: unless-stopped
